public enum TokenType {
    SELECT, FROM, WHERE, AND, OR, TRUE, FALSE,
    IDENTIFIER, NUMBER, STRING,
    COMMA, STAR, SEMICOLON,
    EQUAL, GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, NOT_EQUAL,
    EOF, INVALID
}
